name: Release

on:
  workflow_dispatch:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - uses: ivanvc/abuild-releaser-action@main
        with:
          author: spacefall <spacefall@5822.it>
          rsa_public_key: ${{ secrets.RSA_PUBLIC_KEY }}
          rsa_private_key: ${{ secrets.RSA_PRIVATE_KEY }}